language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
install: NODE_ENV=development npm install
before_script: pushd ./test/test_app/ && npm install && popd && NODE_ENV=development node -r "@doodad-js/make/make" . make
script: npm run travis_app_test && npm run travis_cli_test