dist: trusty
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - $HOME/build/clean
env:
  - NODE_ENV=development
  - NODE_ENV=production
before_install:
  - set -e
  - set -o pipefail
  - git clone --depth=1 https://github.com/doodadjs/travis_scripts.git ~/travis_scripts
  - chmod +x ~/travis_scripts/install.sh
install:
  - set -e
  - set -o pipefail
  - export DD_TARGET=$HOME/build/clean
  - export DD_REPOS=`cd $TRAVIS_BUILD_DIR/.. && pwd`
  - mkdir -p $DD_TARGET
  - cd $DD_TARGET
  - ~/travis_scripts/install.sh
  - cd node_modules/@doodad-js/npc
  - pushd test/test_app
  - npm install
  - popd
  - node -r "@doodad-js/make/make" . make
script:
  - set -e
  - set -o pipefail
  - npm run travis_app_test
  - npm run travis_cli_test
