language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_script: NODE_ENV=development npm install && node -r "@doodad-js/make/make" . make
script: npm run travis_app_test && npm run travis_cli_test